In [1]:
import duckdb

con = duckdb.connect()

con.sql("""
    SELECT *
    FROM read_parquet('data/parquet/**/*.parquet', hive_partitioning=true)
    LIMIT 10
""").df()

,Quarter,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,...,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109,Month,Year
0,4,1,7,2023-10-01,9E,20363,9E,N909XJ,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
1,4,2,1,2023-10-02,9E,20363,9E,N298PQ,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
2,4,3,2,2023-10-03,9E,20363,9E,N153PQ,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
3,4,4,3,2023-10-04,9E,20363,9E,N678CA,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
4,4,5,4,2023-10-05,9E,20363,9E,N678CA,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
5,4,6,5,2023-10-06,9E,20363,9E,N200PQ,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
6,4,7,6,2023-10-07,9E,20363,9E,N153PQ,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
7,4,8,7,2023-10-08,9E,20363,9E,N903XJ,4800,11193,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
8,4,9,1,2023-10-09,9E,20363,9E,N135EV,4800,11423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023
9,4,10,2,2023-10-10,9E,20363,9E,N298PQ,4800,11423,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,2023

In [2]:
con.sql("""
    DESCRIBE
    SELECT *
    FROM read_parquet('data/parquet/**/*.parquet', hive_partitioning=true)
""").df()

           column_name column_type null   key default extra
0              Quarter      BIGINT  YES  None    None  None
1           DayofMonth      BIGINT  YES  None    None  None
2            DayOfWeek      BIGINT  YES  None    None  None
3           FlightDate     VARCHAR  YES  None    None  None
4    Reporting_Airline     VARCHAR  YES  None    None  None
..                 ...         ...  ...   ...     ...   ...
105      Div5WheelsOff      DOUBLE  YES  None    None  None
106        Div5TailNum      DOUBLE  YES  None    None  None
107       Unnamed: 109      DOUBLE  YES  None    None  None
108              Month      BIGINT  YES  None    None  None
109               Year      BIGINT  YES  None    None  None

[110 rows x 6 columns]